#!/usr/bin/env bash
#
# Ensure the required dep programs are available
#
# Author: Claus
# Date: 2025-11-26
# License: MIT

code=0

check() {
	echo -n "$*... "
	if ! "$@"; then
		echo 'error'
		code=1
	fi
}

check command -v bash
check command -v curl
check command -v pandoc

exit "$code"
