#!/usr/bin/env bash
#
# Ensure the required dep programs are available
#
# Author: lovetravelsfaster
# Date: 2025-12-01
# License: MIT

RELEASE_ID=$(date +%Y-%m-%d_%H-%M)
TARGET="deploy@lakelabs:/srv/www/clauslol/releases/$(echo $RELEASE_ID)"
rsync -avz --delete _site/ "$TARGET/"