#!/usr/bin/env bash
#
# Convert the list of .md files in journal_entries/ into
# 1. A JSON formatted list for the journal page index
# 2. A journal entry HTML page for each .md file
#
# Author: lovetravelsfaster
# Date: 2025-11-27
# License: MIT

varname=$1

journal_entries_md_dir=journal_entries

baselink='https://claus.lol'

# this is a "journal_entry" object in the final json
read -d '' -r json <<-"EOF"
{
	"title": $title,
	"description": $description,
	"link": $link,
	"number": $number
}
EOF

# Extract YAML metadata (between the first pair of --- lines)
# to stdout
filter_yaml_metadata() {
    local file=$1
    awk '
        /^---$/ {
            if (start) {
                exit
            }
            start = 1
            next
        }
        start {
            print
        }
    ' "$file"
}

# Parses the actual YAML lines and sends
# key/values to stdout
parse_yaml_metadata() {
    local file=$1 line key val

    while IFS= read -r line; do
        # skip empty and comment lines
        [[ -z $line || $line == \#* ]] && continue

        # must contain a colon
        [[ $line == *:* ]] || continue

        # Split into key and value
        key=${line%%:*}
        val=${line#*:}

        # Trim whitespace
        key=$(awk '{$1=$1}1' <<< "$key")
        val=$(awk '{$1=$1}1' <<< "$val")

        printf '%s=%s\n' "$key" "$val"

    done < <(filter_yaml_metadata "$file")
}


objects=()
for entry in $journal_entries_md_dir/*.md; do

	# The journal_entry.html "template" has a few 
	# placeholders we need to replace. Journal number, 
	# Journal date, and Journal title

	# Get filename and date
	filename="$(basename "$entry")"
	filename="${filename%.*}"
	date="${filename:0:10}"

	# Get metadata from each entry into
	# key/values of an assoc array
	declare -A metadata=()
	while IFS='=' read -r k v; do
	    metadata["$k"]="$v"
	done < <(parse_yaml_metadata "$entry")

	# Debugging, can delete when done
	echo "Title: ${metadata[title]}" >&2
	echo "Description: ${metadata[description]}" >&2
	echo "Number: ${metadata[number]}" >&2

	# Using filename without extension to name
	# the folder of the entry, entry itself will
	# be index.html
	#entry_dir=_site/j/"$filename"
	entry_dir="_site/j/${metadata[number]}"
	mkdir -p "$entry_dir"

	# Replacing all the placeholders in 
	# journal_entry.html. Two of them with
	# simple in-line variable comprehension,
	# the actual JOURNAL_ENTRY for the HTML
	# snippet is done by reading from stdin
	# piped from the pandoc command.
	pandoc $entry -f markdown -t html | \
	sed \
		-e "s|{{JOURNAL_NUMBER}}|${metadata[number]}|g" \
		-e "s|{{JOURNAL_DATE}}|$date|g" \
		-e "/{{JOURNAL_ENTRY}}/{
		         r /dev/stdin
		         d
		     }" \
		  static/journal_entry.html > "$entry_dir"/index.html

	# Append to objects array for later writing json
	object=$(jq -nc \
		--arg title "${metadata[title]}" \
		--arg description "${metadata[description]}" \
		--arg link "$baselink/j/${metadata[number]}" \
		--argjson number "${metadata[number]}" \
		"$json"
	)
	objects+=("$object")
done

# generate output JSON
printf -v now '%(%s)T' -1
output=$(printf '%s\n' "${objects[@]}" | jq -n \
    --argjson date "$now" \
    --arg link "$baselink" \
    '{
        "name": "Claus LOL",
        "site": $link,
        "generated": $date,
        "journal_entries": [inputs]
     }'
)

# print the data (optionally as jsonp if the first arg is set)
if [[ -n $varname ]]; then
	output="const $varname = $output;"
fi
echo "$output"
